export interface LibraryTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  items: { text: string; requires_photo: boolean }[];
}

export const LIBRARY_CATEGORIES = [
  "Food Safety",
  "Health & Safety",
  "Hygiene",
  "Equipment",
  "Closing",
  "Staff",
] as const;

export const complianceLibrary: LibraryTemplate[] = [
  {
    id: "lib-food-safety-opening",
    title: "Opening Food Safety Check",
    description: "Daily opening checks to ensure food safety standards are met before service begins.",
    category: "Food Safety",
    items: [
      { text: "Check fridge temperatures are between 1°C and 5°C", requires_photo: true },
      { text: "Check freezer temperatures are at -18°C or below", requires_photo: true },
      { text: "Inspect all food deliveries for damage or expiry", requires_photo: false },
      { text: "Verify date labels on all prep containers", requires_photo: false },
      { text: "Ensure raw and cooked foods are stored separately", requires_photo: false },
      { text: "Check handwashing stations are stocked (soap, towels)", requires_photo: false },
      { text: "Confirm pest control traps are intact", requires_photo: false },
    ],
  },
  {
    id: "lib-temperature-log",
    title: "Temperature Log",
    description: "Record fridge, freezer, and hot-holding temperatures throughout the day.",
    category: "Food Safety",
    items: [
      { text: "Record Walk-in Fridge #1 temperature", requires_photo: true },
      { text: "Record Walk-in Fridge #2 temperature", requires_photo: true },
      { text: "Record Freezer temperature", requires_photo: true },
      { text: "Record Prep Fridge temperature", requires_photo: true },
      { text: "Record hot-holding unit temperature (if applicable)", requires_photo: true },
      { text: "Flag any out-of-range readings to manager", requires_photo: false },
    ],
  },
  {
    id: "lib-allergen-control",
    title: "Allergen Control Checklist",
    description: "Verify allergen handling procedures and labelling compliance.",
    category: "Food Safety",
    items: [
      { text: "Allergen information displayed and up to date", requires_photo: false },
      { text: "All prep surfaces cleaned between allergen and non-allergen food", requires_photo: false },
      { text: "Separate utensils used for allergen-free preparation", requires_photo: false },
      { text: "Staff briefed on today's allergen specials/changes", requires_photo: false },
      { text: "Allergen-free ingredients stored separately and labelled", requires_photo: true },
    ],
  },
  {
    id: "lib-fire-safety",
    title: "Fire Safety Inspection",
    description: "Weekly fire safety checks for alarms, extinguishers, and exit routes.",
    category: "Health & Safety",
    items: [
      { text: "All fire exits are unobstructed and clearly marked", requires_photo: true },
      { text: "Fire extinguishers are in place and serviced (check tags)", requires_photo: true },
      { text: "Fire alarm panel shows no faults", requires_photo: true },
      { text: "Emergency lighting is functional", requires_photo: false },
      { text: "Fire evacuation plan is displayed and legible", requires_photo: false },
      { text: "Fire doors close fully and latch properly", requires_photo: false },
    ],
  },
  {
    id: "lib-first-aid",
    title: "First Aid Kit Check",
    description: "Monthly check to ensure first aid kits are stocked and accessible.",
    category: "Health & Safety",
    items: [
      { text: "First aid kit location is clearly signed", requires_photo: false },
      { text: "Plasters (assorted sizes) are stocked", requires_photo: false },
      { text: "Sterile dressings and bandages are available", requires_photo: false },
      { text: "Disposable gloves are available", requires_photo: false },
      { text: "Antiseptic wipes/spray are in date", requires_photo: false },
      { text: "Eye wash solution is available and in date", requires_photo: false },
      { text: "First aid log book is present", requires_photo: true },
    ],
  },
  {
    id: "lib-slip-trip-fall",
    title: "Slip, Trip & Fall Hazard Check",
    description: "Daily walkthrough to identify and mitigate slip, trip, and fall hazards.",
    category: "Health & Safety",
    items: [
      { text: "Floors are clean and dry (no spills)", requires_photo: false },
      { text: "Wet floor signs are available and used when needed", requires_photo: false },
      { text: "Walkways and corridors are clear of obstructions", requires_photo: false },
      { text: "Floor mats are flat and not curled at edges", requires_photo: false },
      { text: "Outdoor paths and steps are clear and well-lit", requires_photo: false },
      { text: "Cables and cords are secured and not across walkways", requires_photo: false },
    ],
  },
  {
    id: "lib-restroom-cleanliness",
    title: "Restroom Cleanliness Audit",
    description: "Hourly or shift-based restroom inspection for cleanliness and supplies.",
    category: "Hygiene",
    items: [
      { text: "Toilets and urinals are clean", requires_photo: false },
      { text: "Sinks and counters are clean and dry", requires_photo: false },
      { text: "Soap dispensers are filled", requires_photo: false },
      { text: "Paper towels / hand dryers are functional", requires_photo: false },
      { text: "Bins are emptied and lined", requires_photo: false },
      { text: "Floors are clean and dry", requires_photo: false },
      { text: "Mirror and fixtures are clean", requires_photo: false },
      { text: "Sign inspection log sheet", requires_photo: true },
    ],
  },
  {
    id: "lib-handwashing-station",
    title: "Handwashing Station Check",
    description: "Verify all handwashing stations are stocked and functional.",
    category: "Hygiene",
    items: [
      { text: "Hot and cold running water is available", requires_photo: false },
      { text: "Antibacterial soap dispenser is filled", requires_photo: false },
      { text: "Paper towels are stocked", requires_photo: false },
      { text: "Handwashing procedure poster is displayed", requires_photo: false },
      { text: "Waste bin is empty and lined", requires_photo: false },
    ],
  },
  {
    id: "lib-kitchen-deep-clean",
    title: "Kitchen Deep Clean",
    description: "Weekly or monthly deep cleaning checklist for the kitchen area.",
    category: "Hygiene",
    items: [
      { text: "Ovens and grills cleaned inside and out", requires_photo: true },
      { text: "Hood filters and extractor fans cleaned", requires_photo: true },
      { text: "Behind and under all equipment cleaned", requires_photo: false },
      { text: "Walls and ceilings wiped down", requires_photo: false },
      { text: "Grease traps emptied and cleaned", requires_photo: true },
      { text: "All shelving wiped and sanitised", requires_photo: false },
      { text: "Drains cleaned and free-flowing", requires_photo: false },
      { text: "Pest control points checked", requires_photo: false },
    ],
  },
  {
    id: "lib-equipment-maintenance",
    title: "Equipment Maintenance Log",
    description: "Regular checks to ensure all kitchen equipment is functioning safely.",
    category: "Equipment",
    items: [
      { text: "All gas connections secure and no leaks detected", requires_photo: false },
      { text: "Electrical cords and plugs in good condition", requires_photo: false },
      { text: "Oven/stove burners ignite and heat properly", requires_photo: false },
      { text: "Dishwasher rinse temperature meets standard (82°C+)", requires_photo: true },
      { text: "Blenders, mixers, and slicers have guards in place", requires_photo: false },
      { text: "Ice machine cleaned and producing clear ice", requires_photo: false },
      { text: "Report any faulty equipment to maintenance", requires_photo: false },
    ],
  },
  {
    id: "lib-refrigeration-check",
    title: "Refrigeration Unit Check",
    description: "Dedicated inspection of all refrigeration units for proper function.",
    category: "Equipment",
    items: [
      { text: "Door seals are intact and closing properly", requires_photo: false },
      { text: "No excessive ice build-up in freezers", requires_photo: true },
      { text: "Internal thermometer matches external display", requires_photo: true },
      { text: "Units are not overloaded (air can circulate)", requires_photo: false },
      { text: "Condenser coils are clean and dust-free", requires_photo: false },
      { text: "Drain pans are clean and draining properly", requires_photo: false },
    ],
  },
  {
    id: "lib-closing-checklist",
    title: "End of Day Closing Checklist",
    description: "Complete closing procedures to secure the premises at end of business.",
    category: "Closing",
    items: [
      { text: "All cooking equipment turned off", requires_photo: false },
      { text: "Gas supply turned off (if applicable)", requires_photo: false },
      { text: "All food stored correctly and covered", requires_photo: false },
      { text: "Fridges and freezers closed and sealed", requires_photo: false },
      { text: "Kitchen surfaces wiped and sanitised", requires_photo: false },
      { text: "Floors swept and mopped", requires_photo: false },
      { text: "Bins emptied and new liners placed", requires_photo: false },
      { text: "Lights turned off in non-essential areas", requires_photo: false },
      { text: "Doors and windows locked", requires_photo: false },
      { text: "Alarm system activated", requires_photo: false },
    ],
  },
  {
    id: "lib-cash-handling",
    title: "Cash Handling Audit",
    description: "End of shift cash handling and reconciliation checklist.",
    category: "Closing",
    items: [
      { text: "Count cash drawer and record totals", requires_photo: true },
      { text: "Reconcile drawer total with POS report", requires_photo: false },
      { text: "Note and report any discrepancies", requires_photo: false },
      { text: "Secure cash in safe", requires_photo: false },
      { text: "POS terminal logged out and secured", requires_photo: false },
    ],
  },
  {
    id: "lib-uniform-appearance",
    title: "Uniform & Appearance Check",
    description: "Ensure all staff meet uniform and grooming standards before shift.",
    category: "Staff",
    items: [
      { text: "Clean uniform worn (no stains or damage)", requires_photo: false },
      { text: "Name badge visible", requires_photo: false },
      { text: "Hair tied back and/or covered (kitchen staff)", requires_photo: false },
      { text: "No jewellery on hands/wrists (kitchen staff)", requires_photo: false },
      { text: "Appropriate footwear worn (non-slip, closed-toe)", requires_photo: false },
      { text: "Fingernails short and clean, no nail polish (kitchen staff)", requires_photo: false },
    ],
  },
  {
    id: "lib-ppe-compliance",
    title: "PPE Compliance Check",
    description: "Verify all staff have and are using required personal protective equipment.",
    category: "Staff",
    items: [
      { text: "Cut-resistant gloves available for knife work", requires_photo: false },
      { text: "Heat-resistant gloves available for oven use", requires_photo: false },
      { text: "Disposable gloves stocked and used for food handling", requires_photo: false },
      { text: "Non-slip shoes worn by all kitchen staff", requires_photo: false },
      { text: "Safety goggles available for chemical handling", requires_photo: false },
      { text: "All PPE in good condition (no tears or damage)", requires_photo: false },
    ],
  },
];
