project_id = "belpronrmaoebmfqvucv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.merge-link]
    verify_jwt = false
  [functions.merge-fetch-fields]
    verify_jwt = false
  [functions.merge-sync]
    verify_jwt = false
  [functions.apply-hris-mappings]
    verify_jwt = false
  [functions.accept-invite]
    verify_jwt = false
  [functions.send-invite-email]
    verify_jwt = false
